{
    "mypy": "test_files\\static_failure.py:11: error: Name \"unknown_variable\" is not defined \n[name-defined]\n    print(unknown_variable)   #\n          ^\ntest_files\\static_failure.py:15: error: Incompatible return value type (got\n\"str\", expected \"int\")  [return-value]\n        return \"Hello, world!\"   #\n               ^~~~~~~~~~~~~~~\ntest_files\\static_failure.py:30: error: \"Sample\" has no attribute \"age\" \n[attr-defined]\n    print(obj.age)  # age is not defined   #\n          ^~~~~~~\nFound 3 errors in 1 file (checked 1 source file)",
    "pyright": "c:\\Users\\bhamahad\\PycharmProjects\\annotator2\\test_files\\static_failure.py\n  c:\\Users\\bhamahad\\PycharmProjects\\annotator2\\test_files\\static_failure.py:11:7 - error: \"unknown_variable\" is not defined (reportUndefinedVariable)\n  c:\\Users\\bhamahad\\PycharmProjects\\annotator2\\test_files\\static_failure.py:15:12 - error: Type \"Literal['Hello, world!']\" is not assignable to return type \"int\"\n  \u00c2\u00a0\u00c2\u00a0\"Literal['Hello, world!']\" is not assignable to \"int\" (reportReturnType)\n  c:\\Users\\bhamahad\\PycharmProjects\\annotator2\\test_files\\static_failure.py:30:11 - error: Cannot access attribute \"age\" for class \"Sample\"\n  \u00c2\u00a0\u00c2\u00a0Attribute \"age\" is unknown (reportAttributeAccessIssue)\n3 errors, 0 warnings, 0 informations \nWARNING: there is a new pyright version available (v1.1.396 -> v1.1.397).\nPlease install the new version or set PYRIGHT_PYTHON_FORCE_VERSION to `latest`",
    "pyanalyze": "Failed to import .\\test_files\\static_failure.py due to TypeError('can only concatenate str (not \"int\") to str') (code: import_failed)\nIn .\\test_files\\static_failure.py at line 3\n   1: # sample_test.py\n   2: \n   3: def add_numbers(a, b):\n      ^\n   4:     return a + b\n   5: \n   6: \nTraceback (most recent call last):\n  File \"C:\\Users\\bhamahad\\PycharmProjects\\annotator2\\.venv\\lib\\site-packages\\pyanalyze\\name_check_visitor.py\", line 1314, in _load_module\n    return importer.load_module_from_file(\n  File \"C:\\Users\\bhamahad\\PycharmProjects\\annotator2\\.venv\\lib\\site-packages\\pyanalyze\\importer.py\", line 102, in load_module_from_file\n    return import_module(str(abspath), abspath), False\n  File \"C:\\Users\\bhamahad\\PycharmProjects\\annotator2\\.venv\\lib\\site-packages\\pyanalyze\\importer.py\", line 110, in import_module\n    spec.loader.exec_module(module)\n  File \"<frozen importlib._bootstrap_external>\", line 790, in exec_module\n  File \"<frozen importlib._bootstrap>\", line 228, in _call_with_frames_removed\n  File \"C:\\Users\\bhamahad\\PycharmProjects\\annotator2\\test_files\\static_failure.py\", line 8, in <module>\n    result: int = add_numbers(\"5\", 10)\n  File \"C:\\Users\\bhamahad\\PycharmProjects\\annotator2\\test_files\\static_failure.py\", line 4, in add_numbers\n    return a + b\nTypeError: can only concatenate str (not \"int\") to str"
}